/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.swlc.bolton.notifier;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Connection conn = null;
        try {
            Properties dpProperties = new Properties();
            File dbFile = new File("settings/application.properties");
            FileReader dbFileReader = new FileReader(dbFile);
            dpProperties.load(dbFileReader);

            conn = (Connection) DriverManager.getConnection("jdbc:mysql://" + dpProperties.getProperty("db.ip") + "/" + dpProperties.getProperty("db.name"), (String) dpProperties.getProperty("db..user"), (String) dpProperties.getProperty("db.password"));

        } catch (SQLException ex) {
            // handle any errors
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
