/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.swlc.bolton.notifier;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    Connection conn = null;
try {
    conn = DriverManager.getConnection("jdbc:mysql://localhost/oom_notifier?" +
                                   "user=athukorala&password=athukoralaAdmin@123");
    System.out.println("conn:"+conn);
      

} catch (SQLException ex) {
    // handle any errors
    System.out.println("SQLException: " + ex.getMessage());
    System.out.println("SQLState: " + ex.getSQLState());
    System.out.println("VendorError: " + ex.getErrorCode());
}
    }
}
